services:
  llm-server:
    container_name: llm-server
    build: .
    ports:
      - "21009:21009"
    volumes:
      - ${HOME}/.cache/huggingface/hub:/root/.cache/huggingface/hub
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:21009/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      stockelper:
        aliases:
          - llm-server
    environment:
      - REQUESTS_TIMEOUT=300

  langfuse-server:
    image: langfuse/langfuse:2
    restart: always
    container_name: langfuse-server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "21003:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt  
      ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
      NEXTAUTH_URL: http://localhost:3000
      TELEMETRY_ENABLED: "false"
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: "false"
      LANGFUSE_INIT_ORG_ID: "1"
      LANGFUSE_INIT_ORG_NAME: "stockelper"
      LANGFUSE_INIT_PROJECT_ID: "1"
      LANGFUSE_INIT_PROJECT_NAME: "stockelper"
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: "pk-lf-example-public-key"
      LANGFUSE_INIT_PROJECT_SECRET_KEY: "sk-lf-example-secret-key"
      LANGFUSE_INIT_USER_EMAIL: "user@example.com"
      LANGFUSE_INIT_USER_NAME: "stockelper" 
      LANGFUSE_INIT_USER_PASSWORD: "password123"
    networks:
      stockelper:
        aliases:
          - langfuse-server

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-db.sh:/docker-entrypoint-initdb.d/init-multiple-db.sh:ro
    networks:
      - stockelper

volumes:
  postgres_data:

networks:
  stockelper:
    driver: bridge
    name: stockelper
    external: true
