version: '3.10'

networks:
  stockelper:
    driver: bridge  # 네트워크 드라이버를 명시적으로 설정
    name: stockelper
    external: true

services:
  vectordb:
    image: milvusdb/milvus
    container_name: vectordb
    restart: always
    command: milvus run standalone  1> /dev/null
    networks:
      - stockelper  # 동일 네트워크 설정
    ports:
      - 21001:19530
    volumes:
      - ./volumes/milvus:/var/lib/milvus
      - type: bind
        source: ./embedEtcd.yaml
        target: /milvus/configs/embedEtcd.yaml
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3

  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    networks:
      - stockelper  # 동일 네트워크 설정
    ports:
      - "21002:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: mongodb_data
    external: true
